[package]
name = "worlds-sim-rust"
version = "0.1.0"
edition = "2021"
resolver = "2"

[features]
debug = ["save/debug"]
render = ["bevy/bevy_asset", "bevy/bevy_winit", "bevy/render", "save/render"]
default = ["render", "debug"]

[dependencies.save]
path = "save"

[dependencies.bevy]
version = "0.8"
default-features = false
