[package]
name = "worlds-history-sim-rs"
version = "0.1.0"
edition = "2021"
resolver = "2"

[profile]
release = { strip = "symbols", lto = "thin", opt-level = "z" }

[features]
logging = ["planet/logging"]
globe_view = ["planet/globe_view", "render"]
render = ["bevy/bevy_asset", "bevy/bevy_winit", "bevy/x11", "bevy/wayland", "bevy/render", "planet/render"]
default = ["render", "logging"]

[dependencies.planet]
path = "planet"
default-features = false

[dependencies.bevy]
version = "0.8"
default-features = false
