[package]
name = "worlds-sim-rust"
version = "0.1.0"
edition = "2021"
resolver = "2"

[features]
debug = ["planet/debug"]
globe_view = ["planet/globe_view", "render"]
render = ["bevy/bevy_asset", "bevy/bevy_winit", "bevy/x11", "bevy/wayland", "bevy/render", "planet/render", "dep:bevy_pancam"]
default = ["render", "debug"]

[dependencies.planet]
path = "planet"
default-features = false

[dependencies.bevy]
version = "0.8"
default-features = false

[dependencies.bevy_pancam]
version = "0.6.1"
optional = true
