[package]
name = "worlds-sim-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.save]
path = "save"

[dependencies.bevy]
version = "0.8"
default-features = false
features = ["bevy_asset", "bevy_winit", "bevy_scene", "render"]
