[package]
name = "save"
version = "0.1.0"
edition = "2021"

[features]
debug = []
render = ["bevy/render"]

[dependencies.noise]
version = "0.7.0"
default-features = false

[dependencies.rand]
version = "0.8.5"

[dependencies.bevy]
version = "0.8"
default-features = false
