---
name: pre-release
on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre-release"
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-12]
        features: ["debug,render", render, "debug", ""]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Build binary
        run: |
          cargo build --release --no-default-features --features=${{ matrix.features }}

      - name: Upload binary
        if: ${{ matrix.os }}=="windows"
        uses: actions/upload-artifact@v3
        with:
          name: worlds-rs.exe
          path: target/release/worlds-sim-rust.exe
      - name: Uplaod binary
        if: ${{ matrix.os }}!="windows"
        uses: actions/upload-artifact@v3
        with:
          name: world-rs
          path: target/release/worlds-sim-rust
